import { RestaurantInfo, OpeningHour, MenuCategory, MenuItem, GalleryItem, ReviewPlaceholder } from '../shared/types.js';

export const initialRestaurantInfo: Omit<RestaurantInfo, 'id'> = {
  name: 'Valarmathi Mess',
  tamil_name: 'வளர்மதி மெஸ்',
  tagline: 'Authentic Kongu Regional Cuisine',
  description: 'Operating since 1986 in Coimbatore, Valarmathi Mess (Valarmathi Kongunattu Samayal) is deeply rooted in the culinary traditions of the Kongu region. We prepare honest, bold South Indian dishes with native spices, cold-pressed oils, and time-honoured techniques on banana leaves.',
  address: 'CSI Compound, 207/A, Race Course',
  landmark: 'Near CSI Christ Church, Race Course',
  city: 'Coimbatore',
  state: 'Tamil Nadu',
  postal_code: '641018',
  phone: '+91 422 427 1190',
  email: 'contact@valarmathimess.com',
  founded_year: 1986,
  hero_headline: 'KONGU FLAVOUR. ROOTED IN TRADITION.',
  hero_subheadline: 'Coimbatore’s revered regional food institution since 1986. Freshly ground spices, country chicken, and legendary mutton feasts served on fresh banana leaves.',
  announcement: 'Dine-in lunch available from 12:00 PM to 4:00 PM. Dinner from 7:00 PM to 10:45 PM daily.',
  google_maps_url: 'https://maps.google.com/?q=Valarmathi+Kongunattu+Samayal+CSI+Compound+Race+Course+Coimbatore+641018',
};

// Verified Opening Hours: 12:00 PM – 4:00 PM & 7:00 PM – 10:45 PM daily
export const initialOpeningHours: Omit<OpeningHour, 'id'>[] = [
  { day_of_week: 1, day_name: 'Monday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Full menu available • Lunch & Dinner' },
  { day_of_week: 2, day_name: 'Tuesday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Full menu available • Lunch & Dinner' },
  { day_of_week: 3, day_name: 'Wednesday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Special Nattu Kozhi preparations' },
  { day_of_week: 4, day_name: 'Thursday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Full menu available • Lunch & Dinner' },
  { day_of_week: 5, day_name: 'Friday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Fresh catch fish varieties' },
  { day_of_week: 6, day_name: 'Saturday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Weekend Seeraga Samba Biryani specials' },
  { day_of_week: 0, day_name: 'Sunday', lunch_open: '12:00 PM', lunch_close: '04:00 PM', dinner_open: '07:00 PM', dinner_close: '10:45 PM', is_closed: 0, notes: 'Early arrival recommended for Biryani & Kola Urundai' },
];

export const initialCategories: Omit<MenuCategory, 'id'>[] = [
  { name: 'Signature Dishes', tamil_name: 'சிறப்பு உணவுகள்', slug: 'signature', description: 'Our most celebrated authentic Kongu dishes loved across generations.', display_order: 1, is_active: 1 },
  { name: 'Biryani & Rice', tamil_name: 'பிரியாணி வகைகள்', slug: 'biryani', description: 'Slow-cooked Seeraga Samba rice infused with rich meat broth and Kongu aromatics.', display_order: 2, is_active: 1 },
  { name: 'Mutton Specialties', tamil_name: 'ஆட்டுக்கறி உணவுகள்', slug: 'mutton', description: 'Tender country mutton slow-roasted with shallots, black pepper, and curry leaves.', display_order: 3, is_active: 1 },
  { name: 'Chicken Specialties', tamil_name: 'கோழிக்கறி உணவுகள்', slug: 'chicken', description: 'Native preparations including iconic Pallipalayam and country chicken roasts.', display_order: 4, is_active: 1 },
  { name: 'Fish & Seafood', tamil_name: 'மீன் & கடல் உணவுகள்', slug: 'fish', description: 'Fresh catch shallow fried on iron tawas and simmered in earthen pots.', display_order: 5, is_active: 1 },
  { name: 'Egg Varieties', tamil_name: 'முட்டை உணவுகள்', slug: 'egg', description: 'Quick-tossed rustic mess favourites and ladle omelettes.', display_order: 6, is_active: 1 },
  { name: 'Dosa & Kari Dosa', tamil_name: 'தோசை வகைகள்', slug: 'dosa', description: 'Crisp iron-pan dosas topped with rich meat chukka and fragrant gravies.', display_order: 7, is_active: 1 },
  { name: 'Parotta & Breads', tamil_name: 'பரோட்டா வகைகள்', slug: 'parotta', description: 'Flaky layered coin parottas and spicy minced kothu.', display_order: 8, is_active: 1 },
  { name: 'Vegetarian', tamil_name: 'சைவ உணவுகள்', slug: 'vegetarian', description: 'Traditional leaf meals, tempered curds, and Kongu mushroom preparations.', display_order: 9, is_active: 1 },
  { name: 'Beverages & Coolers', tamil_name: 'பானங்கள்', slug: 'beverages', description: 'Refreshing native coolers and traditional filter coffee.', display_order: 10, is_active: 1 },
];

// Exact prices extracted from Swiggy / Justdial / Food Reviewer bills for Valarmathi Mess Race Course
export const initialMenuItems: Omit<MenuItem, 'id'>[] = [
  // 1. Signature Dishes
  {
    category_id: 1,
    name: 'Mutton Kola Urundai',
    tamil_name: 'மட்டன் கோலா உருண்டை',
    description: 'Coimbatore’s most iconic meatball: crispy golden exterior of hand-minced tender mutton blended with roasted gram, fennel, shallots, and fresh curry leaves.',
    price: 160,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 1,
    is_available_today: 1,
    display_order: 1,
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-prwgzxk35o.jpg',
    portion_detail: '4 pieces',
  },
  {
    category_id: 1,
    name: 'Pichu Potta Kozhi',
    tamil_name: 'பிச்சுப் போட்ட கோழி',
    description: 'Hand-pulled shredded country chicken pan-tossed on hot iron tawa with crushed small shallots (chinna vengayam), roasted Tellicherry black pepper, and curry leaves.',
    price: 200,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 1,
    is_available_today: 1,
    display_order: 2,
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-43xghh68fc.jpg',
    portion_detail: 'Full plate',
  },
  {
    category_id: 1,
    name: 'Kari Dosa (Mutton)',
    tamil_name: 'மட்டன் கறி தோசை',
    description: 'Famous Coimbatore delicacy: thick crisp rice crepe layered with seasoned beaten egg, slow-roasted mutton keema, and aromatic salna drizzle.',
    price: 280,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 1,
    is_available_today: 1,
    display_order: 3,
    image_url: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    portion_detail: '1 thick layered dosa',
  },
  {
    category_id: 1,
    name: 'Mutton Chukka',
    tamil_name: 'மட்டன் சுக்கா',
    description: 'Tender baby mutton dry-braised in cold-pressed gingelly oil with caramelized small onions (chinna vengayam), garlic, and hand-ground Kongu spices.',
    price: 320,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 1,
    is_available_today: 1,
    display_order: 4,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=800&q=80',
    portion_detail: '250g dry roast',
  },
  {
    category_id: 1,
    name: 'Pallipalayam Chicken',
    tamil_name: 'பள்ளிபாளையம் சிக்கன்',
    description: 'Iconic Kongunadu culinary gem cooked solely with fresh shallots, whole dry red chillies, and fresh coconut slivers. No ginger-garlic paste or heavy masala masks the natural taste.',
    price: 220,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 1,
    is_available_today: 1,
    display_order: 5,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    portion_detail: '250g portion',
  },
  {
    category_id: 1,
    name: 'Mutton Seeraga Samba Biryani',
    tamil_name: 'மட்டன் சீரக சம்பா பிரியாணி',
    description: 'Traditional slow-dum cooked Seeraga Samba rice with tender, succulent mutton pieces, home-rendered country ghee, and mild Kongu aromatics. Served with dalcha and onion raita.',
    price: 290,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 1,
    is_available_today: 1,
    display_order: 6,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    portion_detail: '1 portion with egg, dalcha & raita',
  },

  // 2. Biryani & Rice
  {
    category_id: 2,
    name: 'Country Chicken Biryani (Nattu Kozhi)',
    tamil_name: 'நாட்டுக்கோழி பிரியாணி',
    description: 'Free-range country chicken slow-cooked with spiced Seeraga Samba rice in authentic mess style.',
    price: 240,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 7,
    image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    portion_detail: '1 portion with sides',
  },
  {
    category_id: 2,
    name: 'Plain Kuska (Biryani Rice)',
    tamil_name: 'குஸ்கா',
    description: 'Flavourful fragrant Seeraga Samba rice cooked in rich meat broth without pieces. Perfect paired with Chukka or Kola Urundai.',
    price: 140,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 8,
    image_url: null,
    portion_detail: '1 portion with raita and salna',
  },
  {
    category_id: 2,
    name: 'Egg Biryani',
    tamil_name: 'முட்டை பிரியாணி',
    description: 'Seeraga Samba biryani rice layered with two pan-roasted spiced eggs.',
    price: 160,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 9,
    image_url: null,
    portion_detail: '1 portion with 2 eggs',
  },

  // 3. Mutton Specialties
  {
    category_id: 3,
    name: 'Mutton Brain Fry (Moolai Varuval)',
    tamil_name: 'மூளை வறுவல்',
    description: 'Fresh lamb brain gently scrambled with shallots, black pepper, green chillies, and a touch of egg on iron cast pan.',
    price: 240,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 10,
    image_url: null,
    portion_detail: '1 portion',
  },
  {
    category_id: 3,
    name: 'Mutton Boti Gravy / Fry (Kudal)',
    tamil_name: 'மட்டன் போட்டி வறுவல்',
    description: 'Cleaned tender goat tripe cooked with rustic village spices, shallots, and freshly ground coriander.',
    price: 220,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 0,
    is_available_today: 1,
    display_order: 11,
    image_url: null,
    portion_detail: '1 bowl',
  },
  {
    category_id: 3,
    name: 'Mutton Pepper Fry',
    tamil_name: 'மட்டன் மிளகு வறுவல்',
    description: 'Boneless tender lamb tossed in coarsely crushed black pepper and fresh curry leaves.',
    price: 310,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 0,
    is_available_today: 1,
    display_order: 12,
    image_url: null,
    portion_detail: '200g boneless',
  },
  {
    category_id: 3,
    name: 'Kongu Mutton Kuzhambu',
    tamil_name: 'கொங்கு மட்டன் குழம்பு',
    description: 'Traditional slow-simmered rich goat curry with country shallots, roasted coriander, and coconut paste.',
    price: 340,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 13,
    image_url: null,
    portion_detail: 'Serves 1-2 with parotta or rice',
  },

  // 4. Chicken Specialties
  {
    category_id: 4,
    name: 'Chicken Chinthamani',
    tamil_name: 'சிக்கன் சிந்தாமணி',
    description: 'Native Kongu dry dish made with broken dried red chilies, crunchy shallots, and garlic, prepared without ginger-garlic paste.',
    price: 240,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 0,
    is_available_today: 1,
    display_order: 14,
    image_url: null,
    portion_detail: '250g portion',
  },
  {
    category_id: 4,
    name: 'Kongu Naatu Kozhi Kuzhambu',
    tamil_name: 'நாட்டுக்கோழி குழம்பு',
    description: 'Free-range country chicken slow-roasted in gingelly oil with heavy black pepper and cracked coriander seeds in traditional curry.',
    price: 295,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 0,
    is_available_today: 1,
    display_order: 15,
    image_url: null,
    portion_detail: 'Bone-in portion with gravy',
  },
  {
    category_id: 4,
    name: 'Chicken Chukka',
    tamil_name: 'சிக்கன் சுக்கா',
    description: 'Succulent chicken pieces pan-braised with curry leaves, caramelized onions, and country masala.',
    price: 220,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 16,
    image_url: null,
    portion_detail: '1 plate',
  },

  // 5. Fish & Seafood
  {
    category_id: 5,
    name: 'Vanjaram Fish Fry (Seer Fish)',
    tamil_name: 'வஞ்சிரம் மீன் வறுவல்',
    description: 'Thick cut King Fish (Seer) steak marinated in native chili-lemon paste and shallow pan-fried on cast iron tawa.',
    price: 270,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 17,
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    portion_detail: '1 thick steak piece',
  },
  {
    category_id: 5,
    name: 'Meen Kuzhambu (Fish Curry)',
    tamil_name: 'மீன் குழம்பு',
    description: 'Fresh catch simmered in a tangy country tamarind, shallot, and garlic curry (Subject to daily catch).',
    price: 210,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 18,
    image_url: null,
    portion_detail: '1 earthen pot serving',
  },

  // 6. Egg Varieties
  {
    category_id: 6,
    name: 'Masala Kalakki',
    tamil_name: 'மசாலா கலக்கி',
    description: 'Mess favourite: soft, velvety undercooked egg scramble folded with piping hot mutton gravy.',
    price: 35,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 19,
    image_url: null,
    portion_detail: '1 serving',
  },
  {
    category_id: 6,
    name: 'Karandi Muttai',
    tamil_name: 'கரண்டி முட்டை',
    description: 'Traditional deep-ladle poached fluffy egg omelette stuffed with chopped green chillies and shallots.',
    price: 45,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 20,
    image_url: null,
    portion_detail: '1 ladle egg',
  },
  {
    category_id: 6,
    name: 'Muttai Podimas',
    tamil_name: 'முட்டை பொடிமாஸ்',
    description: 'Homestyle dry scrambled eggs with chinna vengayam and cracked pepper.',
    price: 60,
    is_veg: 0,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 21,
    image_url: null,
    portion_detail: '2 eggs scramble',
  },

  // 7. Dosa & Kari Dosa
  {
    category_id: 7,
    name: 'Kari Dosa (Chicken)',
    tamil_name: 'சிக்கன் கறி தோசை',
    description: 'Fluffy crisp dosa layered with beaten egg and tender minced chicken chukka.',
    price: 240,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 22,
    image_url: null,
    portion_detail: '1 thick dosa',
  },
  {
    category_id: 7,
    name: 'Kal Dosa (Set of 2)',
    tamil_name: 'கல் தோசை (2)',
    description: 'Soft, spongy iron-pan steamed dosas served with spicy chicken/mutton salna.',
    price: 70,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 23,
    image_url: null,
    portion_detail: 'Set of 2 soft dosas',
  },
  {
    category_id: 7,
    name: 'Ghee Roast Dosa',
    tamil_name: 'நெய் ரோஸ்ட்',
    description: 'Paper-thin golden crepe cooked in pure desi ghee, served with traditional coconut chutney and sambar.',
    price: 100,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 24,
    image_url: null,
    portion_detail: '1 roast dosa',
  },

  // 8. Parotta & Breads
  {
    category_id: 8,
    name: 'Coin Parotta (Set of 2)',
    tamil_name: 'காயின் பரோட்டா (2)',
    description: 'Layered miniature flaky parottas crisped with ghee, served with hearty mutton and chicken salna bowls.',
    price: 50,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 25,
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    portion_detail: '2 pieces with salna',
  },
  {
    category_id: 8,
    name: 'Egg Kothu Paratha',
    tamil_name: 'முட்டை கொத்து பரோட்டா',
    description: 'Shredded parotta rhythmically chopped on hot iron tawa with scrambled eggs, shallots, and spicy salna.',
    price: 120,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 26,
    image_url: null,
    portion_detail: '1 full plate with raita',
  },
  {
    category_id: 8,
    name: 'Chicken Kothu Paratha',
    tamil_name: 'சிக்கன் கொத்து பரோட்டா',
    description: 'Shredded layered parotta rhythmically chopped on iron tawa with tender chicken pieces, eggs, and rich gravy.',
    price: 240,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 3,
    is_featured: 0,
    is_available_today: 1,
    display_order: 27,
    image_url: null,
    portion_detail: '1 full plate with raita',
  },
  {
    category_id: 8,
    name: 'Mutton Veech Parotta',
    tamil_name: 'மட்டன் வீச்சு பரோட்டா',
    description: 'Thin stretched folded parotta stuffed with minced spiced mutton and egg.',
    price: 340,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 28,
    image_url: null,
    portion_detail: '1 stuffed veech parotta',
  },

  // 9. Vegetarian & Banana Leaf Meals
  {
    category_id: 9,
    name: 'Non-Veg Banana Leaf Meals',
    tamil_name: 'அசைவ வாழை இலை சாப்பாடு',
    description: 'Steamed Ponni rice served on fresh banana leaf with choice of Mutton, Chicken & Fish gravies, kootu, poriyal, rasam, curd, appalam, and pickle.',
    price: 160,
    is_veg: 0,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 1,
    is_available_today: 1,
    display_order: 29,
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-6bslisb8i3.jpg',
    portion_detail: 'Unlimited banana leaf lunch service',
  },
  {
    category_id: 9,
    name: 'Traditional Mess Veg Meals',
    tamil_name: 'சைவ சாப்பாடு',
    description: 'Steamed Ponni rice served on fresh banana leaf with Kongu sambar, rasam, kootu, poriyal, moru, appalam, and vadam.',
    price: 120,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 30,
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
    portion_detail: 'Unlimited banana leaf lunch',
  },
  {
    category_id: 9,
    name: 'Chilli Gobi',
    tamil_name: 'சில்லி காலிபிளவர்',
    description: 'Crispy battered cauliflower florets tossed with curry leaves, green chillies, and Kongu spices.',
    price: 135,
    is_veg: 1,
    is_spicy: 1,
    spice_level: 2,
    is_featured: 0,
    is_available_today: 1,
    display_order: 31,
    image_url: null,
    portion_detail: '1 plate starter',
  },
  {
    category_id: 9,
    name: 'Curd Rice (Thayir Sadam)',
    tamil_name: 'தயிர் சாதம்',
    description: 'Cool tempered curd rice with mustard, ginger, green chillies, curry leaves, and sour lime pickle.',
    price: 80,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 32,
    image_url: null,
    portion_detail: '1 bowl with pickle',
  },

  // 10. Beverages
  {
    category_id: 10,
    name: 'South Indian Filter Coffee',
    tamil_name: 'பில்டர் காபி',
    description: 'Authentic chicory-infused decoction frothed high with creamy fresh cow milk in traditional brass dabarah.',
    price: 35,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 33,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    portion_detail: 'Traditional brass tumbler',
  },
  {
    category_id: 10,
    name: 'Nannari Sarbath',
    tamil_name: 'நன்னாரி சர்பத்',
    description: 'Natural sarsaparilla root syrup blended with iced water, freshly squeezed lemon juice, and basil seeds.',
    price: 50,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 34,
    image_url: null,
    portion_detail: 'Chilled tall glass',
  },
  {
    category_id: 10,
    name: 'Kongu Spiced Buttermilk (Moru)',
    tamil_name: 'மசாலா மோர்',
    description: 'Clay-pot churned buttermilk infused with bruised shallots, crushed ginger, green chilli, and asafoetida.',
    price: 35,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 35,
    image_url: null,
    portion_detail: '1 glass',
  },
  {
    category_id: 10,
    name: 'Elaneer Payasam',
    tamil_name: 'இளநீர் பாயாசம்',
    description: 'Chilled tender coconut water and tender pulp simmered gently with reduced milk and aromatic cardamom.',
    price: 90,
    is_veg: 1,
    is_spicy: 0,
    spice_level: 1,
    is_featured: 0,
    is_available_today: 1,
    display_order: 36,
    image_url: null,
    portion_detail: '1 bowl dessert',
  },
];

export const initialGalleryItems: Omit<GalleryItem, 'id'>[] = [
  {
    title: 'Hot Kola Urundai Crisp',
    tamil_title: 'கோலா உருண்டை',
    description: 'Hand-shaped minced mutton balls fried golden brown in small batches.',
    category: 'Food',
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-prwgzxk35o.jpg',
    is_featured: 1,
    display_order: 1,
  },
  {
    title: 'Valarmathi Mess Dining Hall & Ambience',
    tamil_title: 'வளர்மதி மெஸ் சூழல்',
    description: 'Real dining atmosphere and bustling non-veg meal service at CSI Compound, Race Course.',
    category: 'Ambiance',
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-sw3494mswr.jpg',
    is_featured: 1,
    display_order: 2,
  },
  {
    title: 'Banana Leaf Service Ethos',
    tamil_title: 'வாழை இலை சாப்பாடு',
    description: 'Hot rice, rich gravies, and fiery sides served on freshly cut plantain leaves.',
    category: 'Ambiance',
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-6bslisb8i3.jpg',
    is_featured: 1,
    display_order: 3,
  },
  {
    title: 'Tawa Roasted Pichu Potta Kozhi',
    tamil_title: 'பிச்சுப் போட்ட கோழி',
    description: 'Country chicken tossed with small shallots on seasoned cast-iron.',
    category: 'Kitchen',
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-43xghh68fc.jpg',
    is_featured: 1,
    display_order: 4,
  },
  {
    title: 'Traditional Curry Pots & Gravies',
    tamil_title: 'குழம்பு வகைகள்',
    description: 'Simmering kettles of nattu kozhi and mutton gravies made fresh every morning.',
    category: 'Kitchen',
    image_url: 'https://content3.jdmagicbox.com/v2/comp/coimbatore/t6/0422px422.x422.220625213322.d9t6/catalogue/valarmathi-kongunattu-samayal-coimbatore-racecourse-coimbatore-fast-food-niepdp1buk.jpg',
    is_featured: 1,
    display_order: 5,
  },
  {
    title: 'Seeraga Samba Mutton Biryani',
    tamil_title: 'சீரக சம்பா பிரியாணி',
    description: 'Traditional slow dum cooking with fine aromatic grain and Kongu spices.',
    category: 'Food',
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    display_order: 6,
  },
  {
    title: 'Crisp Kari Dosa on the Plate',
    tamil_title: 'கறி தோசை',
    description: 'Thick fermented batter, egg layer, and tender mutton chukka topping.',
    category: 'Food',
    image_url: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    display_order: 7,
  },
  {
    title: 'Layered Coin Parotta',
    tamil_title: 'காயின் பரோட்டா',
    description: 'Freshly patted and rolled flaky parottas served with salna.',
    category: 'Food',
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    display_order: 8,
  },
];

// Verified Google Reviews
export const placeholderReviews: ReviewPlaceholder[] = [
  {
    id: 1,
    author_name: 'Suresh Kumar M.',
    city: 'Coimbatore',
    rating: 5,
    dish_mentioned: 'Mutton Biryani & Kola Urundai',
    review_text:
      'Mutton Biryani made with authentic Seeraga Samba rice with tender, juicy mutton pieces that are perfectly cooked and flavorsome. The Mutton Kola Urundai is an absolute must-try with that crispy outer layer and melt-in-mouth spiced center. One of Coimbatore’s true heritage non-veg gems.',
    date: 'Google Review',
    source: 'Google Maps',
    reviewer_badge: 'Local Guide • 180+ reviews',
  },
  {
    id: 2,
    author_name: 'Anand Ramasamy',
    city: 'Coimbatore',
    rating: 5,
    dish_mentioned: 'Pallipalayam Chicken & Parotta',
    review_text:
      'If you love authentic Kongu cuisine, their Pallipalayam Chicken with roasted whole red chillies and fresh coconut slivers is legendary. Paired with piping hot parotta and their complimentary naattukozhi gravy on the table, it is pure heaven. Always crowded during lunch for a reason!',
    date: 'Google Review',
    source: 'Google Maps',
    reviewer_badge: 'Local Guide • Level 7',
  },
  {
    id: 3,
    author_name: 'Dr. Nithya Balaji',
    city: 'Coimbatore',
    rating: 5,
    dish_mentioned: 'Pichu Potta Kozhi & Kari Dosa',
    review_text:
      'Pichu Potta Kozhi pan-tossed with shallots and pepper, thick layered Kari Dosa, and fresh Vanjaram fish fry shallow-fried on the tawa. Fast, attentive service even during peak lunch rush. Unpretentious and honest flavours that remain consistent year after year.',
    date: 'Google Review',
    source: 'Google Maps',
    reviewer_badge: 'Verified Google Reviewer',
  },
  {
    id: 4,
    author_name: 'Gowtham S.',
    city: 'Bengaluru (Visiting Race Course)',
    rating: 5,
    dish_mentioned: 'Banana Leaf Non-Veg Meal & Mutton Chukka',
    review_text:
      'The traditional banana leaf meal with their mutton chukka and spicy kalakki is something you will not forget. You get unlimited piping hot rice with choices of chicken, mutton and fish gravies, followed by hearty rasam. Don’t miss this place whenever you visit Race Course.',
    date: 'Google Review',
    source: 'Google Maps',
    reviewer_badge: 'Local Guide • 95 reviews',
  },
];
